### ISSUE TITLE
getting error: During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by mataldomen** [ErichStyger/Hexiwear_v2#3]
Hi,

Firstly I want to thank You for your work. It was really helpful for my project :D.

I have one big problem. I little change your code and I use it for connection raspbery with 3 arduinos nano 33 ble. Everything works fine but sometimes I receive this error:
I paste last properly receiving data and error.

```
12.700000000000003
done!
<pexpect.pty_spawn.spawn object at 0xb6760e90>
command: /usr/bin/gatttool
args: ['/usr/bin/gatttool', '-I']
buffer (last 100 chars): b'\x1b[0;94m[C6:95:A2:AF:F6:79]\x1b[0m[LE]> '
before (last 100 chars): b' 06 2c 0e 29 c4 2d f6 2b 0d 29 8b 2e 10 '
after: b'\r\n'
match: <re.Match object; span=(40, 42), match=b'\r\n'>
match_index: 0
exitstatus: None
flag_eof: False
pid: 934
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1


Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 111, in expect_loop
    incoming = spawn.read_nonblocking(spawn.maxread, timeout)
  File "/usr/lib/python3/dist-packages/pexpect/pty_spawn.py", line 482, in read_nonblocking
    raise TIMEOUT('Timeout exceeded.')
pexpect.exceptions.TIMEOUT: Timeout exceeded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "GetData2.py", line 75, in <module>
    child.expect("handle: 0x000b 	 value:"or"handle: 0x000c 	 value:", timeout=10 )
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 341, in expect
    timeout, searchwindowsize, async_)
  File "/usr/lib/python3/dist-packages/pexpect/spawnbase.py", line 369, in expect_list
    return exp.expect_loop(timeout)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 119, in expect_loop
    return self.timeout(e)
  File "/usr/lib/python3/dist-packages/pexpect/expect.py", line 82, in timeout
    raise TIMEOUT(msg)
pexpect.exceptions.TIMEOUT: Timeout exceeded.
<pexpect.pty_spawn.spawn object at 0xb6760e90>
command: /usr/bin/gatttool
args: ['/usr/bin/gatttool', '-I']
buffer (last 100 chars): b'\x1b[0;94m[C6:95:A2:AF:F6:79]\x1b[0m[LE]> char-read-uuid 0x2A19\r\n\x1b[0;94m[C6:95:A2:AF:F6:79]\x1b[0m[LE]> '
before (last 100 chars): b'\x1b[0;94m[C6:95:A2:AF:F6:79]\x1b[0m[LE]> char-read-uuid 0x2A19\r\n\x1b[0;94m[C6:95:A2:AF:F6:79]\x1b[0m[LE]> '
after: <class 'pexpect.exceptions.TIMEOUT'>
match: None
match_index: None
exitstatus: None
flag_eof: False
pid: 934
child_fd: 5
closed: False
timeout: 30
delimiter: <class 'pexpect.exceptions.EOF'>
logfile: None
logfile_read: None
logfile_send: None
maxread: 2000
ignorecase: False
searchwindowsize: None
delaybeforesend: 0.05
delayafterclose: 0.1
delayafterterminate: 0.1
searcher: searcher_re:
    0: re.compile(b'handle: 0x000b \t value:')

```
I dont have any ideas why this error occurs. It occurs after random time working. If You have some advise about that I will be really thankfull.

My code:

```
import pexpect
import time
import sys
import os

# ---------------------------------------------------------------------
# function to transform hex string like "0a cd" into signed integer
# ---------------------------------------------------------------------
def hexStrToInt(hexstr):
    val = int(hexstr[0:2],16) + (int(hexstr[3:5],16)<<8)
    if ((val&0x8000)==0x8000): # treat signed 16bits
        val = -((val^0xffff)+1)
    return val
# ---------------------------------------------------------------------


device = "C6:95:A2:AF:F6:79" # Arduino 2 Żolte
print("czytanie")

if len(sys.argv) == 2:
    device = str(sys.argv[1])

# Run gatttool interactively.
child = pexpect.spawn("gatttool -I")

# Connect to the device.
print("Connecting to:"),
print(device)

NOF_REMAINING_RETRY = 3

while (True):
    try:
        child.sendline("connect {0}".format(device))
        child.expect("Connection successful", timeout=5)
    except pexpect.TIMEOUT:
        NOF_REMAINING_RETRY = NOF_REMAINING_RETRY-1
        if (NOF_REMAINING_RETRY>0):
          print ("timeout, retry...")
          continue
        else:
          print ("timeout, giving up.")
          break
    else:
        print("Connected!")
        break
x=0
while(x<1):
    #if NOF_REMAINING_RETRY>0:
    unixTime = int(time.time())
    unixTime += 60*60 # GMT+1
    unixTime += 60*60 # added daylight saving time of one hour

    #open file

    file = open("Arduino2.csv", "a")
    if (os.path.getsize("Arduino2.csv")==0):
        file.write("ttime\tAccX\tAccY\tAccZ\tGyroX\tGyroY\tGyroZ\tMagX\tMagY\tMagZ\n")

        file.write(device)
        file.write("\t")
    file.write(str(unixTime)) # Unix timestamp in seconds
    file.write("\t")
    #print(unixTime)

      # Accelerometer
    child.sendline("char-read-uuid 0x2A19")
    #time.sleep(0.05)
    print(child)
    child.expect("handle: 0x000b 	 value:", timeout=10 )
    child.expect("\r\n", timeout=10)
    #print("Accel:  "),
    #print(child.before),

    #for x in range(12):
    file.write(str((float(hexStrToInt(child.before[1:6]))/100)-100))
    file.write("\t")
    #file.write(str((float(hexStrToInt(child.before[7:12]))/100)-100))
    #file.write("\t")
    print(str((float(hexStrToInt(child.before[1:6]))/100)-100))
    #file.write(str(float(hexStrToInt(child.before[12:17]))/100))
    #file.write("\t")


    file.write("\n")
    file.close()
    print("done!")

    #else:
        #print("FAILED!")
        #sys.exit(-1)

sys.exit(0)
print("finished")
```

**Comment by ErichStyger** [comment]
It seems to me that the Arduino code is the problem. I'm not 100% sure because I'm not using Arduino. I suggest you debug that Arduino code why it happens?

**Comment by ErichStyger** [comment]
Closing issue. Without having your hardware (I'm not using Arduino libraries), I'm not sure what I can do?

**Comment by mataldomen** [comment]
Thank You for answer.

I found a problem. I send to raspberry array of chars which is defined into string. When i received zero Arduino thought it was end of string. And that Was a reason. On Arduino i don't have any other options then array of chars to send a lot of data by one characteristic. Probably I have to sent 6 floats in 6 characteristics.

I have one last question.
How fast reading data your RaspberryPI on Your code ? On which frequency ?
I read data from my code maximum 6-7 times for a one second and it is too slow for data from IMU. 

Do You do this faster ? 
How and why ? Mayby You have some idea how I can increase speed of reading data?

I use Raspberry Pi Zero W 512MB Ram – WiFi + BT 4.1

**Comment by ErichStyger** [comment]
I'm reading data with about 1 Hz only, I don't need more. In my view you cannot use a Raspberry Pi for anything realtime as you have in mind, it is simply the wrong approach: The BLE is not able to transmit more than a 20-28 bytes in a message anyway: that protocol is for low power and slow data, not for high speed. If you want to use wireless with higher speed, use WiFi (but this needs more power too).
